-- MySQL Script generated by MySQL Workbench
-- Tue Feb 11 09:15:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gymcpic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `gymcpic`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`rol` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gymcpic`.`centroFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`centroFormacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gymcpic`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`tipoUsuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gymcpic`.`programaFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`programaFormacion` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `fkCentroFormacion` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkCentroFormacion`
    FOREIGN KEY (`fkCentroFormacion`)
    REFERENCES `gymcpic`.`centroFormacion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gymcpic`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`usuario` (
  `id` INT NOT NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `fechaNac` DATE NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `peso` DOUBLE NOT NULL,
  `estatura` DOUBLE NOT NULL,
  `imc` DOUBLE NOT NULL,
  `grupoSanguineo` VARCHAR(3) NOT NULL,
  `afectacionFisica` TEXT NULL,
  `observaciones` TEXT NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `fkIdRol` INT NOT NULL,
  `fkTipoUsuario` INT NOT NULL,
  `fkCentroFormacion` INT NULL,
  `fkProgramaFormacion` INT NULL,
  CONSTRAINT `fkIdRol`
    FOREIGN KEY (`id` , `fkIdRol`)
    REFERENCES `gymcpic`.`rol` (`id` , `id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkTipoUsuario`
    FOREIGN KEY (`fkTipoUsuario`)
    REFERENCES `gymcpic`.`tipoUsuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkCentroFormacion`
    FOREIGN KEY (`fkCentroFormacion`)
    REFERENCES `gymcpic`.`centroFormacion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkProgramaFormacion`
    FOREIGN KEY (`fkProgramaFormacion`)
    REFERENCES `gymcpic`.`programaFormacion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gymcpic`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`actividad` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gymcpic`.`registroIngreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`registroIngreso` (
  `id` INT NOT NULL,
  `fechaIn` DATETIME NOT NULL,
  `fechaOut` DATETIME NOT NULL,
  `fkIdUsuarioGym` INT NOT NULL,
  `fkIdActividad` INT NOT NULL,
  `fkIdEntrenador` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdUsuarioGym`
    FOREIGN KEY (`fkIdUsuarioGym`)
    REFERENCES `gymcpic`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdActividad`
    FOREIGN KEY (`fkIdActividad`)
    REFERENCES `gymcpic`.`actividad` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdEntrenador`
    FOREIGN KEY (`fkIdEntrenador`)
    REFERENCES `gymcpic`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gymcpic`.`controlProgreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymcpic`.`controlProgreso` (
  `id` INT NOT NULL,
  `fechaControl` DATE NOT NULL,
  `peso` FLOAT NOT NULL,
  `estatura` FLOAT NOT NULL,
  `pecho` FLOAT NULL,
  `espalda` FLOAT NULL,
  `cintura` FLOAT NULL,
  `cadera` FLOAT NULL,
  `brazoIzq` FLOAT NULL,
  `brazoDer` FLOAT NULL,
  `musloIzq` FLOAT NULL,
  `musloDer` FLOAT NULL,
  `pantorrIzq` FLOAT NULL,
  `pantorrDer` FLOAT NULL,
  `antebrazoIzq` FLOAT NULL,
  `antebrazoDerl` FLOAT NULL,
  `fkIdUsuarioGym` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdUsuarioGym2`
    FOREIGN KEY (`fkIdUsuarioGym`)
    REFERENCES `gymcpic`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
